### ISSUE TITLE
Add doc to deploy to kubernetes

### ISSUE THREAD

**Issue by iainsproat** [specklesystems/speckle-docs#102]
## Problem description

Our documentation for deploying a server is to a [VM (DigitalOcean droplet) with docker-compose](https://speckle.guide/dev/server-setup.html).

Our preferred method of deploying is now to Kubernetes cluster with helm.  This does not currently have a guide.

## Acceptance criteria
`given` a user who wishes to deploy speckle server on kubernetes
`when` they look for documentation
`then` they can find a guide that is comparable to the [existing guide.](https://speckle.guide/dev/server-setup.html)

## Tasks
- [x] Create a new guide
- [x] Update Helm repository README
- [x] update Helm repository Github pages README
